"""
build-gallery.py — CrispyScapes gallery manifest generator
------------------------------------------------------------
Scans images/nsw, vic, tas, nz, europe, other subfolders.
Uses images/favourites as a signal (duplicate files = favourite).
Auto-generates titles from filenames.
Writes gallery-manifest.js.

Run manually:  python build-gallery.py
Auto-runs via git pre-commit hook on every commit.
"""

import os, json

# ── Config ────────────────────────────────────────────────────────────────────
REGIONS     = ['nsw', 'vic', 'tas', 'nz', 'europe', 'other']
IMG_DIR     = 'images'
FAV_DIR     = os.path.join(IMG_DIR, 'favourites')
OUTPUT_FILE = 'gallery-manifest.js'
EXTENSIONS  = {'.webp', '.jpg', '.jpeg', '.png'}

# Words to always uppercase in auto-generated titles
ACRONYMS = {'tnt', 'knp', 'nsw', 'nz', 'ii', 'iii', 'iv', 'vi'}

# ── Title generator ───────────────────────────────────────────────────────────
def title_from_filename(filename):
    name = os.path.splitext(filename)[0].replace('-', ' ')
    words = []
    for word in name.split():
        if word.lower() in ACRONYMS:
            words.append(word.upper())
        else:
            words.append(word.capitalize())
    return ' '.join(words)

# ── Scan ──────────────────────────────────────────────────────────────────────
favourites = set()
if os.path.isdir(FAV_DIR):
    for f in os.listdir(FAV_DIR):
        if os.path.splitext(f)[1].lower() in EXTENSIONS:
            favourites.add(f.lower())

gallery = []
for region in REGIONS:
    folder = os.path.join(IMG_DIR, region)
    if not os.path.isdir(folder):
        continue
    files = sorted(
        f for f in os.listdir(folder)
        if os.path.splitext(f)[1].lower() in EXTENSIONS
    )
    for fname in files:
        categories = [region]
        if fname.lower() in favourites:
            categories.append('favourites')
        gallery.append({
            'src':        f'{IMG_DIR}/{region}/{fname}',
            'categories': categories,
            'title':      title_from_filename(fname),
        })

# ── Write manifest ────────────────────────────────────────────────────────────
with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by build-gallery.py — do not edit manually\n')
    f.write('var GALLERY_DATA = ')
    json.dump(gallery, f, indent=2, ensure_ascii=False)
    f.write(';\n')

print(f'gallery-manifest.js written — {len(gallery)} images across {len(REGIONS)} regions')
print(f'  Favourites tagged: {sum(1 for g in gallery if "favourites" in g["categories"])}')
